global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using MobileLiteStoreCeep.Models;
global using MobileLiteStoreCeep.Services;
global using MobileLiteStoreCeep.ViewModels;
global using MobileLiteStoreCeep.Views;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Threading.Tasks;
